language: java
branches:
    only:
        - master
git:
    depth: 100
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
install: mvn install -DskipTests=true
script: mvn clean integration-test

cache:
  directories:
  - $HOME/.m2
